# Base image
# FROM python:alpine        # Slimmer but less package support
#
# Better for FLASK in combination with FastAPI, production ready
FROM python:3.12-slim 

RUN apt-get update && apt-get install -y procps grep net-tools curl 

# Copy app folder (templates and views)
# This folder is a bind mount ./app in the project folder
COPY . /app

# Set working directory for subsequent commands
WORKDIR /app

# Install python dependencies
RUN pip install -r requirements.txt

EXPOSE 8080
# Expose port for debugging (Don't put behind the port on same line = error!)
EXPOSE 5670


# Command to run when the container starts. 
#   - Disabled because you’re overriding in docker-compose
# ENTRYPOINT ["python", "app.py"] 